export const LOAD_EMPLOYEES = "LOAD_EMPLOYEES";
export const SORT_NAME_ASC= "SORT_NAME_ASC";
export const SORT_NAME_DES = "SORT_NAME_DES";
export const FILTER_FIELD_NAME = "FILTER_FIELD_NAME";
export const FILTER_FIELD_NUMBER = "FILTER_FIELD_NUMBER";